# Generated by Django 4.2.5 on 2023-10-23 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='adddress',
            new_name='address',
        ),
    ]
